# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: false

# Setup
title:               Development and Stuff
tagline:             'Ethan's development blog'
description:         'A development blog for whatever projects I'm working on'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ethan Hunter
  url:               https://github.com/Spaceman1701
  email:             fcspaceman@@gmail.com

# Custom vars
version:             1.0.0
